resolver: lts-15.4
compiler: ghc-8.10.1
packages:
- .

extra-deps:
- /Users/rjhala/research/liquidhaskell
- /Users/rjhala/research/liquidhaskell/liquid-ghc-prim
- /Users/rjhala/research/liquidhaskell/liquid-base
- /Users/rjhala/research/liquidhaskell/liquid-containers
- /Users/rjhala/research/liquidhaskell/liquid-fixpoint
- text-format-0.3.2
- optics-0.2
# Required for the 8.10.1 build
- Diff-0.3.4
- aeson-1.4.7.1
- git: https://github.com/well-typed/optics.git
  commit: 0a4940cc927df3f50151692282f8b148bf326886
  subdirs:
    - optics-core
    - optics-th
